### ISSUE TITLE
Debug selected node white

### ISSUE THREAD

**Issue by mrm** [Hyzeta/vscode-theme-github-light#4]
Hi, 

First of all thanks for this great theme, I've been using it for quite some time. Unfortunately I've encountered a bug where the focused node in the debug panel has a white foreground color even though all the relevant theme variables seem to be set correctly (as far as I can tell):

![focus](https://user-images.githubusercontent.com/141798/66481619-93b11100-eaa1-11e9-9d7b-1140fba5b6dd.png)

With the non-gray version it's white foreground on a white background making it invisible.

**Comment by chuling** [comment]
Sorry for hearing this, I take a look at it.

**Comment by yunlingz** [comment]
Sorry for hearing this, I will take a look at it.

**Comment by yunlingz** [comment]
It seems some other color theme have this problem too (but not MS' build in one), maybe MS add some new color token, it may take me some time to find it out...
*****
To solve this problem,  adding background to `activeSelection` seems to be the only way...
*****
<https://github.com/microsoft/vscode/blob/master/src/vs/platform/theme/common/colorRegistry.ts#L233>

**Comment by yunlingz** [comment]
I check vscode's src, it seems that `listFocusAndSelectionBackground` and `listFocusAndSelectionForeground` are controlling this behavior.
<https://github.com/microsoft/vscode/blob/ab0eb6de2d5fb4563385d98f302f78caa1767efd/src/vs/base/browser/ui/list/listWidget.ts#L872-L873>

but there is no registry entry in `src/vs/platform/theme/common/colorRegistry.ts`
<https://github.com/microsoft/vscode/blob/ab0eb6de2d5fb4563385d98f302f78caa1767efd/src/vs/platform/theme/common/colorRegistry.ts#L230-L247>

Bug reported to vscode in <https://github.com/microsoft/vscode/issues/82165>.

**Comment by mrm** [comment]
Thanks for looking into this so quickly!

**Comment by yunlingz** [comment]
Confirm that this will be fixed in <https://github.com/microsoft/vscode/commit/bad4cf565f32a6cc95f8ade49326cf2da0c8f4a0>

**Comment by yunlingz** [comment]
Should be fixed in 7.10.0, please let me know if you find any problems.
