### ISSUE TITLE
Currently selected item in QuickInput popup is indistinguishable

### ISSUE THREAD

**Issue by nawordar** [Hyzeta/vscode-theme-github-light#6]
QuickInput is a list that is shown e.g. when changing language mode
![image](https://user-images.githubusercontent.com/26769700/68551242-24656e80-040b-11ea-8e7f-b25930dfa090.png)
I don't know which item is selected, because it has the same background and text colour. \
My suggestion is to use a little darker background colour and a pink font colour like when hovering with mouse.

**Comment by yunlingz** [comment]
In the old version, selected item has a darker background. I will take a look at this and fix it in the new version, but recently I'm a little busy with academic research...so maybe I will not commit the patch as soon as possible...

**Comment by nawordar** [comment]
Thank you :)

**Comment by yunlingz** [comment]
Should be fixed in 7.10.0, please let me know if you find any problems.
